WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = PDB1;

-- Clean up Simpson's schema if it exists
SET SERVEROUTPUT ON;
DECLARE
   v_user_exists NUMBER;
BEGIN
   SELECT COUNT(*) INTO v_user_exists FROM all_users WHERE username = 'SIMPSONS';
   IF v_user_exists > 0 THEN
      EXECUTE IMMEDIATE 'DROP USER SIMPSONS CASCADE';
      DBMS_OUTPUT.PUT_LINE('Old SIMPSONS schema has been dropped.');
   END IF;
END;
/

-- Create user with provided password (passed as &1)
CREATE USER simpsons IDENTIFIED BY "&1";

-- Grant unlimited tablespace to allow creating objects on any tablespace (including default)
GRANT UNLIMITED TABLESPACE TO simpsons;

GRANT CREATE SESSION, CREATE TABLE TO simpsons;

-- SIMPSONS."CHARACTERS" definition

CREATE TABLE "SIMPSONS"."CHARACTERS" 
   (	"ID" NUMBER(*,0), 
	"CHARACTER_ID" NUMBER(*,0), 
	"name" VARCHAR2(100), 
	"NORMALIZED_NAME" VARCHAR2(100), 
	"SEX" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- SIMPSONS.EPISODES definition

CREATE TABLE "SIMPSONS"."EPISODES" 
   (	"ID" NUMBER(*,0), 
	"EPISODE_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(100), 
	"ORIGINAL_AIR_DATE" VARCHAR2(100), 
	"PRODUCTION_CODE" VARCHAR2(100), 
	"SEASON" NUMBER(*,0), 
	"NUMBER_IN_SEASON" NUMBER(*,0), 
	"NUMBER_IN_SERIES" NUMBER(*,0), 
	"US_VIEWERS_IN_MILLIONS" FLOAT(63), 
	"views" NUMBER(*,0), 
	"IMDB_RATING" FLOAT(63), 
	"IMDB_VOTES" NUMBER(*,0), 
	"IMAGE_URL" VARCHAR2(100), 
	"VIDEO_URL" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- SIMPSONS.LOCATIONS definition

CREATE TABLE "SIMPSONS"."LOCATIONS" 
   (	"ID" NUMBER(*,0), 
	"LOCATION_ID" NUMBER(*,0), 
	"name" VARCHAR2(100), 
	"NORMALIZED_NAME" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- SIMPSONS.SCRIPT_LINES definition

CREATE TABLE "SIMPSONS"."SCRIPT_LINES" 
   (	"ID" NUMBER(*,0), 
	"SL_ID" NUMBER(*,0), 
	"EPISODE_ID" NUMBER(*,0), 
	"number" NUMBER(*,0), 
	"RAW_TEXT" VARCHAR2(1000), 
	"TIMESTAMP_IN_MS" NUMBER(*,0), 
	"SPEAKING_LINE" BOOLEAN, 
	"CHARACTER_ID" NUMBER(*,0), 
	"LOCATION_ID" NUMBER(*,0), 
	"RAW_CHARACTER_TEXT" VARCHAR2(1000), 
	"RAW_LOCATION_TEXT" VARCHAR2(100), 
	"SPOKEN_WORDS" VARCHAR2(1000), 
	"NORMALIZED_TEXT" VARCHAR2(1000), 
	"WORD_COUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
